### ISSUE TITLE
Clone someone's AC codes

### ISSUE THREAD

**Issue by xalanq** [xalanq/cf-tool#19]
There is a easy way to clone ourselves codes by this bash script
```bash
for((i=1;i<=2000;i++)); do cf pull ac $i; done
```

But it cannot clone other's codes and seems like not good. 
So, I decide to add a new command `clone` for cloning someone's codes.

**Comment by GaurangTandon** [comment]
Why not just add a new argument to `cf pull`, like `cf pull user=xalanq ...`? By default, let user be the currently logged in user. Thoughts?

**Comment by xalanq** [comment]
By default, if you just use `cf pull`, it will not pull all your codes (It will detect the parameters from the path). So if the tool use `cf pull` to clone all codes, it has to add a new parameter or something else. So I decide to add new command `clone` just like `git clone` :). What do you think?

**Comment by infixint943** [comment]
You could make cf pull in such a way that if no parameter is provided, pull all submissions of a user. Also, @GaurangTandons idea could be implemented.

**Comment by GaurangTandon** [comment]
I am seeing two things here:

1. cloning another user's codes ("But it cannot clone other's codes")
2. cloning all codes written by a user ("By default, if you just use cf pull, it will not pull all your codes")

For each of these we could two new parameters to `cf pull`:

1. `user=<username>` - user whose codes you want to pull
2. `since=<date>` - specify date starting from which you want to pull all the codes

Specifying `since=01/01/1970` would let user, for example, pull all their codes.

I am a bit hesitant about `cf clone` because it will complicate things for the end user (another command to remember). Whereas in most cases user can ignore the `user` and `since` parameters and `cf pull` will do what they want to.

**Comment by xalanq** [comment]
I partially agree with you. But we should remember not only commands but also **the parameters of commands**. Both of them should be simpler.

`cf pull --user=xalanq --since=01/01/1970`

`cf clone xalanq`

I think the latter is simpler.

On the other hand, I think pulling all codes from Codeforces is not a high frequency requirement. If someone want to do that, just see the usage.
